### ISSUE TITLE
Food hunger/saturation restoration is not good as you progress up food tiers.

### ISSUE THREAD

**Issue by fatboychummy** [hugeblank/Bagels_Baking#40]
So this is something I brought up a while ago, but I figured I'd make it into an issue.

A lot of foods you make will actually restore less hunger as you combine more and more food items, which isn't really the best. After all, why craft that sandwich when it restores 1 less point of hunger overall, when you can just eat 2 pieces of bread? Especially when most of the time you'll be eating the food item earlier than when you actually need to eat it because you've hurt yourself and need to heal -- a lot of the hunger/saturation is going to waste.

In essence, the problem currently is that there's no actual incentive to craft the better food items.

My proposition is this:

## Food tiers
Food tiers would be based off of the following
- The amount of different "types" of foods in this food's crafting recipe.

Types would be defined as "vegetable", "fruit", "meat", "grain" ... etc.

Early-game you likely only have one source of food. One type of food, moreso. You combine a bunch of vegetables together and you only get the result of adding the hunger/saturation points together. Kind of like how it is currently.

Mid-game you have two types of food. You combine those together and you get say a 10% hunger/saturation bonus from what adding those types of food together would get, ie: If 2 pieces of bread gives you 5 hunger, and cooked beef gives you 3, adding those together would give you 13 hunger total, but adding 10% would give you 1.3 hunger extra. It isn't a lot, but it's an incentive to use this instead.

Late-game you have all types of food, you combine them all together and get like 10-25% hunger/saturation bonus, depending on how many different types of food you have added to the recipe.

This would provide incentive to use the different food types, because at the moment I've just stuck to eating bread as I actually get *less* from crafting stuff together.

**Comment by hugeblank** [comment]
This issue is partially my fault and the thought process I had behind balancing the foods. What I've been doing for all the food items is rounding down the total hunger and saturation to a level that's more inline with vanilla foods. I'm fairly certain there's some food items where if you combined all of the ingredients it would give you well over 20 hunger (the amount needed to fill the hunger bar from empty). I feel a little wary adding something like that to the game.

What I'll do is rebalance the food items and give them a slight buff. I'll put the test build on OriginsX and see how good/bad it is. If it works out I'll keep the changes for v0.4. The hunger/saturation system is in need of some love anyways.
