### ISSUE TITLE
Game is Crashing

### ISSUE THREAD

**Issue by ReiNAce** [hugeblank/Bagels_Baking#42]
Minecraft is crashing at startup. Idk why. Attached is the crash logs. I am using MultiMC as MC loader in Fabric 0.12.5 for MC 1.17.1.
Please help. Thanks
[crash-2021-11-23_14.45.33-client.txt](https://github.com/hugeblank/Bagels_Baking/files/7586204/crash-2021-11-23_14.45.33-client.txt)

**Comment by hugeblank** [comment]
I'm not exactly in the position to take a more detailed look at the moment, but just a quick scan of the log tells me this is an incompatibility with `better wandering trader`. If that mod isn't critical for you, or the server you're on, then I think you'll be able to launch the game.

**Comment by ReiNAce** [comment]
ok thanks

**Comment by hugeblank** [comment]
Do you have a link to where you got the better wandering trader mod? I'm pretty sure this is a conflict that's out of the scope of Bagel's Baking. You should report the issue there, and link this issue.

**Comment by ReiNAce** [comment]
I already forgot where I downloaded it. Anyways, I already removed the mod anyways, so it is now running.

**Comment by hugeblank** [comment]
alright. I'll look into this and close this when I'm certain it's not BB's fault.

**Comment by hugeblank** [comment]
So the problem here is that Better Wandering Traders is doing something to register whatever they need to for the wandering traders. We use Fabric API for villager trades and profession setup, which means that BWT is incompatible with Fabric API, and Bagel's Baking got caught in the crossfire. I'd recommend reaching out to BWT if you're still keen to do so.
